[package]
name = "account-close"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.3"
solana-program = "1.8.0"
solana-program-test = "1.10.5"
solana-sdk = "1.8.0"
